# Generated by Django 5.0.7 on 2025-04-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='energycategory',
            options={'verbose_name': 'Energy Category', 'verbose_name_plural': 'Energy Categories'},
        ),
        migrations.AlterModelOptions(
            name='energydomain',
            options={'verbose_name': 'Energy Domain', 'verbose_name_plural': 'Energy Domains'},
        ),
        migrations.AlterModelOptions(
            name='energysource',
            options={'verbose_name': 'Energy Source', 'verbose_name_plural': 'Energy Sources'},
        ),
        migrations.AddField(
            model_name='energysource',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='pages.energycategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energysource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsources', to='pages.energysource'),
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.energycategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.energysource')),
            ],
            options={
                'verbose_name': 'Energy Data',
                'verbose_name_plural': 'Energy Data',
            },
        ),
        migrations.DeleteModel(
            name='EnergyConsumption',
        ),
    ]
